version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: eletro_db_container
    environment:
      POSTGRES_DB: eletro_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2024
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
